version: '3.8'

services:
  db:
    container_name: db
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
  api:
    container_name: api
    build: .
    image: burlypronghorn_api
    ports:
      - "7999:7999"
    links:
      - db